# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "latest"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
    # h3 version 4.x breaks backward compatibility and it's not clear how to migrate without loss of functionality
      - dependency-name: "h3"
        versions: ["*"]
    groups:
      python-production:
        dependency-type: "production"
        patterns:
          - "*"