language: python
install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install coveralls
script: 
 - coverage run --source=exhibit -m unittest discover
after_success:
 - coveralls