language: python
dist: focal
python:
 - "3.12"
install:
 - pip install .
 - pip install coverage
 - pip install codecov
script: 
 - coverage run --source=exhibit -m unittest discover
after_success:
 - codecov