name: exhibit
channels:
  - defaults
dependencies:
  - dill=0.3.7
  - numpy=1.25.2
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=11.0.0
  - python=3.10.13
  - pyyaml=6.0.1
  - scipy=1.11.1
  - shapely=2.0.1
  - sqlalchemy=1.4.39
  - pip:
      - h3==3.7.6
