# note that this file is provided for convenience, see exact versions in setup.cfg
name: exhibit_latest
channels:
  - defaults
dependencies:
  - dill
  - numpy
  - pandas
  - pip
  - python
  - pyyaml
  - scipy
  - shapely
  - sqlalchemy
  - pip:
      - h3
      - pyarrow
      - sql-metadata
