# This workflow will install Exhibit and its Python dependencies and run the tests

name: Testing Pull Requests

on:
  pull_request:
    branches: [ "latest" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Install Exhibit and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with unittest
      run: |
        python -m unittest
